version: '3'
services:
  web:
    stdin_open: true
    tty: true
    build: .
    entrypoint:  ./server-entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      OPENAPI_KEY: ${OPENAPI_KEY}
      MUSIXMATCH_KEY: ${MUSIXMATCH_KEY}
    networks:
      webnet:
        ipv4_address: 172.27.0.3

networks:
  webnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
